### ISSUE TITLE
Add a placeholder zine to test against

### ISSUE THREAD

**Issue by dzwdz** [caraesten/dial_a_zine#2]
I've wanted to implement quitting articles early (i'm the same person / among the people that dm'd you on twitter about this), and some basic page navigation, but I wasn't even able to run the server, because I had no zine to host.

**Comment by yaymukund** [comment]
This is very rough, but i have some friends[1] reverse-engineering the format and this might save you some time:

`index.json`:
![image](https://user-images.githubusercontent.com/590450/118810841-3ea3c680-b8a4-11eb-93a9-3c35acecfb10.png)

![screenshot-2021-05-19-13-05-48](https://user-images.githubusercontent.com/590450/118811003-65fa9380-b8a4-11eb-89d1-5a9add90a362.png)

[1] all credit to them.. i just copypasta'd their work :)

**Comment by ocean1212w** [comment]
Hiya that was me, just put up #3 with my example! Nothing fancy

**Comment by caraesten** [comment]
Y'all are amazing. DM me on twitter if you need anything else <3
